version: "3.3"
services:
  spark-master:
    image: cluster-apache-spark:3.3.2
    hostname: "spark-master"
    container_name: "spark-master"
    restart: "always"
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - /export/spark/apps:/opt/spark-apps
       - /export/spark/data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master

  spark-worker-a:
    image: cluster-apache-spark:3.3.2
    hostname: "spark-worker-a"
    container_name: "spark-worker-a"
    restart: "always"
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=8G
      - SPARK_DRIVER_MEMORY=8G
      - SPARK_EXECUTOR_MEMORY=8G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - /export/spark/apps:/opt/spark-apps
       - /export/spark/data:/opt/spark-data

  spark-worker-b:
    image: cluster-apache-spark:3.3.2
    hostname: "spark-worker-b"
    container_name: "spark-worker-b"
    restart: "always"
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=8G
      - SPARK_DRIVER_MEMORY=8G
      - SPARK_EXECUTOR_MEMORY=8G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
       - /export/spark/apps:/opt/spark-apps
       - /export/spark/data:/opt/spark-data

  demo-database:
    image: postgres:15.2-alpine
    hostname: "demo-database"
    container_name: "demo-database"
    restart: "always"
    volumes:
      - /export/spark/pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=${PG_PASSWD}

